### ISSUE TITLE
Check if returned ResultSet is null

### ISSUE THREAD

**Issue by thevella** [thevella/verbose-chainsaw#7]
If the user enters a query that has damaging SQL the code will return a null ResultSet statement. This is so that the user can't kill the database. A message should be shown to notify them and it should not be queried for any output

**Comment by coleman2246** [comment]
Fixed with a control if statement to catch the null.

**Comment by thevella** [comment]
Didn't actually check properly

**Comment by thevella** [comment]
Checked if rs.next() was null instead, then do{}while;. Cole and Mitchell
